myblog/blog/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [path('', views.PostView.as_view(), name='Home'),
               path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
               path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments'),
               path('<int:pk>/add_likes/', views.AddLikes.as_view(), name='add_likes'),
               path('<int:pk>/del_likes/', views.DeLike.as_view(), name='del_likes'),
               path('login/', views.sign_in, name='login'),
               path('logout/', views.sign_out, name='logout'),
               path('register/', views.sign_up, name='register'),
               path('addpost/', views.add_post, name='add_post'),
               path('profile/', views.Profile.as_view(), name='profile')
               ]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class Post(models.Model):
    users = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField('Заголовок записи', max_length=256)
    description = models.TextField('Описание', max_length=8000)
    date = models.DateField('', blank=True, null=True)
    img = models.ImageField('Изображение', upload_to='media/image/%Y/%m/%d/')

    def __str__(self):
        return f'{self.title}, {self.users}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'



class Comments(models.Model):
    users_comment = models.ForeignKey(User, on_delete=models.CASCADE)
    post_id = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)
    text_comments = models.TextField("Комментарий")

    def __str__(self):
        return f'{self.users_comment}, {self.post_id}, {self.text_comments}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Likes(models.Model):
    ip = models.CharField('IP-адрес', max_length=100)
    pos = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

myblog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic import ListView
from .models import Post, Likes, Comments
from .form import LoginForm, RegisterForm, CommentsForm, AddPostForm
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from datetime import datetime
from django.contrib.auth.models import User
from django.core.paginator import Paginator


class Profile(View):
    def get(self, request):
        if request.user.is_authenticated:
            username = request.user
            email = User.objects.filter(is_active=True).values_list('email', flat=True)
            post = Post.objects.filter(users=username).order_by('-id')

        return render(request, 'blog/profile.html', {'my_posts': post})


def add_post(request):
    date_time = datetime.now()
    form = AddPostForm(request.POST, request.FILES)
    if request.method == "POST":
        if request.user.is_authenticated:
            if form.is_valid():
                form = form.save(commit=False)
                form.users = request.user
                form.date = date_time
                form.save()
                messages.success(request, 'Поздравляю пост опубликован!')
                return redirect('profile')
            else:
                print(form.errors)
                messages.success(request, 'Поздравляю пост опубликован!')
        else:
            print(request.user)
    else:
        form = AddPostForm()
    return render(request, 'blog/add_post.html', {'form': form, 'date': date_time})


def sign_in(request):
    '''Функция авторизации'''
    if request.method == 'GET':
        if request.user.is_authenticated:
            return print('')

        form = LoginForm()
        return render(request, 'blog/login.html', {'form': form})

    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('/')

        return render(request, 'blog/login.html', {'form': form})

def sign_out(request):
    '''Функция выхода'''
    logout(request)
    return redirect('/')

def sign_up(request):
    '''Функция регистрации'''
    if request.method == 'GET': # проверка отправлен ли нам GET запрос
        form = RegisterForm()
        return render(request, 'blog/register.html', {'form': form})

    if request.method == 'POST': # проверка отправлен ли нам POST запрос
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Ой что то случилось, возможно вы использовали слабый пароль либо неправильно ввели почту!')
            return render(request, 'blog/register.html', {'form': form})



class PostView(ListView):
    '''Класс основной страницы'''
    def get(self, request):
        global search_count # переменная для счета - результата поиска
        global output_search
        output_search = ""
        search_count = 0 # инициализируем переменную
        search_query = request.GET.get('q', None)
        if search_query:
            posts = Post.objects.filter(Q(title__icontains=search_query) | Q(description__icontains=search_query)).order_by('-id') # Сама механика поиска (вызываем методом)
            search_count = posts.count() # Количество результатов по поиску
            output_search = "Нашли результатов: " + str(search_count)
            if search_count == 0:
                output_search = "Мы ничего не нашли"
        else:
            posts = Post.objects.order_by('-id') # Вытаскиваем статьи и сортируем в обратном порядке дабы выводить
        paginator = Paginator(posts, 2)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'blog/blog.html', {'page_obj': page_obj, 'output_search': output_search})


class PostDetail(View):
    '''Класс детальной страницы статьи'''
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        comment_count = Comments.objects.filter(post_id=post).count() # считаем количество комментариев
        return render(request, 'blog/blog_inside.html', {'post': post, 'com_count': comment_count})



class AddComments(View):
    '''Класс добавления комментария'''
    def post(self, request, pk):
        '''функция обработки комментария'''
        post = Post.objects.get(id=pk)
        form = CommentsForm(request.POST)
        if request.method == "POST":
            if form.is_valid():
                if request.user.is_authenticated:
                    form = form.save(commit=False)
                    form.users_comment = request.user
                    form.post_id = post
                    form.save()
                else:
                    messages.error(request, 'Вы что то неверно ввели')
            else:
                messages.error(request, 'Вы не авторизованы :(')
        else:
            form = CommentsForm()
        return redirect(f'/{pk}')


def get_client_ip(request):
    '''функция получения ip клиента'''
    x_forward_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forward_for:
        ip = x_forward_for.split(',')[0]  #делим наш ip
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class AddLikes(View):
    '''Класс и функция лайка'''
    def get(self, request, pk):
        ip_client = get_client_ip(request) #вытаскиваем ip пользователя
        try:
            Likes.objects.get(ip=ip_client, pos_id=pk)
            return redirect(f'/{pk}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.pos_id = int(pk)
            new_like.save()
            return redirect(f'/{pk}')


class DeLike(View):
    '''Класс и функция дизлайка чи как'''
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            lik = Likes.objects.get(ip=ip_client, pos_id=pk)
            lik.delete()
            return redirect(f'/{pk}')
        except:
            return redirect(f'/{pk}')

# Create your views here.

myblog/templates/blog/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form action="{% url 'add_post' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="title" maxlength="256" required="" id="id_title">
        <textarea name="description" cols="40" rows="10" maxlength="8000" required="" id="id_description"></textarea>
        <time type="text" name="date" required="" id="id_date" style="opacity: 100%" datetime="{{ date_time }}"></time>
        <input type="file" name="img" accept="image/*" id="id_img">
        <input type="submit">
    </form>

</body>
</html>

myblog/templates/blog/header.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'style_for_header.css' %}" type="text/css" media="">
</head>
<header>
    <div class="_main_logo">
        <a href="{% url 'Home' %}"><img src="http://{{ request.get_host }}/static/logo.svg" /></a>
    </div>

    <search>
            <form type="search" name="search" action="/" method="get" style="display: flex;">
                <input type="text" size="40" placeholder="Поиск" class="_search_input_" name="q">
                <button type="submit" class="_button_img_search"><img src="http://{{ request.get_host }}/static/search_m.svg" class="_img_search_button"/></button>
            </form>
    </search>


    <div class="_div_sign_and_login">
        <a href="{% url 'add_post' %}">Добавить статью</a>
        {%if request.user.is_authenticated %}

        <div class="_div_log_in_ava">
            <img src="http://{{ request.get_host }}/static/ava_image.png" class="ava_image_div" />
            <p><a href="{% url 'profile' %}">{{ request.user.username | title }}</a></p>
        </div>

        <div class="_div_out_acc_">
            <a href="{% url 'logout' %}">Выйти из аккаунта</a>
        </div>

        {%else%}

        <div class="_div_log_in_button">
            <a href="{% url 'login' %}">Вход</a>
        </div>



        <div class="_div_sign_in_button">
            <a href="{% url 'register' %}">Регистрация</a>
        </div>
        {%endif%}
    </div>

</header>

myblog/templates/blog/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
	<link rel="stylesheet" href="{% static 'style_register.css' %}" type="text/css" media="">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter" />
</head>
<body>

	<a href="{% url 'Home' %}" class="_a_back_button">Кнопка назад - это сюда</a>

	<div class="_form_sign">
		<div class="_form_in_sign_">
			<div class="_main_logo">
				<a href="{% url 'Home' %}"><img src="http://{{ request.get_host }}/static/logo.svg" /></a>
			</div>

			{% block content %}

			<form action="{% url 'login' %}" method="POST" novalidate>
				{% csrf_token %}
				<h2 class="_h2_form_action_">Тут ты можешь войти в систему</h2>
				<p class="_p_form_action_">Двухсмысленно прозвучало</p>

				<input class="_input_user" type="text" name="username" maxlength="150" autofocus="" required="" id="id_username" placeholder="Имя пользователя"><br />
				<input class="_input_password_one" type="password" name="password" maxlength="65" required="" id="id_password" placeholder="Пароль"><br />
				<input class="_button_submit" type="submit" value="Жмякай сюда" />

				{% if messages %}
				<div class="messages">
					{% for message in messages %}
					<div class="alert {% if message.tags %}alert-{{ message.tags }}" {% endif %}>
						{{ message }}
					</div>
					{% endfor %}
				</div>
				{% endif %}
			</form>




			{% endblock content%}
		</div>
	</div>
</body>
</html>

myblog/templates/blog/paginator.html
{% load static %}
<link rel="stylesheet" href="{% static '_paginator.css' %}" type="text/css" media="">
{% if page_obj.has_other_pages %}
        <div class="pagination">
            <nav style="display: flex;">
                <span class="step-links" style="display: flex;">
                    {% for p in page_obj.paginator.page_range %}
                        {% if page_obj.number == p %}
                        <li>
                            {{ p }}
                        </li>
                        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                        <li>
                            <a href="?page={{ p }}">{{ p }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                </span>
            </nav>
        </div>
{% endif %}

myblog/templates/blog/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static '_profile.css' %}">
</head>
<body style="margin: 0; padding: 0;">
    {% include 'blog/header.html' %}
    <div class="img_profile">
        <div class="_img">
            <img src="http://{{ request.get_host }}/static/Frame50.png" alt="">
        </div>
        <div class="profile_info">
            <div class="username"><p>zxczxczxc</p></div>
            <div class="email"><p>adawdasdwad@huihuihui.sru</p></div>
        </div>
    </div>
    <div class="wrapper">
        <div class="public">
            <div>
                <a class="a" href="https://media.tenor.com/i1rsgMyOFgcAAAAd/cat-cat-love.gif" target="_blank">Мои опубликованные посты</a>
            </div>
            <div>
                <p class="p">Мы все еще работаем над этим</p>
            </div>
        </div>
        <div class="likes">
            <div>
                <a class="a" href="https://media.tenor.com/i1rsgMyOFgcAAAAd/cat-cat-love.gif" target="_blank">Мне понравилось</a>
            </div>
            <div>
                <p class="p">Мы все еще работаем над этим</p>
            </div>
        </div>
        <div class="settings">
            <div>
                <a class="a" href="https://media.tenor.com/i1rsgMyOFgcAAAAd/cat-cat-love.gif" target="_blank">Настройки</a>
            </div>
            <div>
                <p class="p">Мы все еще работаем над этим</p>
            </div>
        </div>
    </div>
</body>
</html>

myblog/templates/blog/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
	<link rel="stylesheet" href="{% static 'style_register.css' %}" type="text/css" media="">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter" />
</head>
<body>
	<a href="{% url 'Home' %}" class="_a_back_button">Кнопка назад - это сюда</a>

	<div class="_form_sign">
		<div class="_form_in_sign_">
			<div class="_main_logo">
				<a href="{% url 'Home' %}"><img src="http://{{ request.get_host }}/static/logo.svg" /></a>
			</div>

			{% block content %}
			<form action='{% url 'register' %}' method="POST" novalidate>
				{% csrf_token %}
				<h2 class="_h2_form_action_">Вот тут у нас регистрация</h2>
				<p class="_p_form_action_">Пароль должен быть из 8 символов! И обязательно две буквы! Одна маленькая, другая большая</p>

				<input class="_input_user" type="text" name="username" maxlength="150" autofocus="" required="" id="id_username" placeholder="Имя пользователя"><br />
				<input class="_input_email" type="email" name="email" maxlength="254" id="id_email" placeholder="Адрес электронной почты"><br />
				<input class="_input_password_one" type="password" name="password1" autocomplete="new-password" required="" id="id_password1" placeholder="Пароль"><br />
				<input class="_input_password_two" type="password" name="password2" autocomplete="new-password" required="" id="id_password2" placeholder="Подтвердите пароль"><br />
				<input class="_button_submit" type="submit" value="Жмякай сюда" />

				{% if messages %}
				<div class="messages">
					{% for message in messages %}
					<div class="alert {% if message.tags %}alert-{{ message.tags }}" {% endif %}>
						{{ message }}
					</div>
					{% endfor %}
				</div>
				{% endif %}

			</form>
			{% endblock content%}
		</div>
	</div>
</body>
</html>